# Generated by Django 6.0.7 on 2026-07-27 13:15

import api.encrypted_fields
import api.models_user
import api.models_work
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="设备组名称")),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("allowed_incomings", models.JSONField(blank=True, default=list, verbose_name="允许来源")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "设备组",
                "verbose_name_plural": "设备组列表",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="StrategyProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=60, unique=True, verbose_name="策略名称")),
                ("config_options", models.JSONField(blank=True, default=dict, verbose_name="配置项")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "策略",
                "verbose_name_plural": "策略列表",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="用户名",
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="邮箱")),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("is_admin", models.BooleanField(default=False, verbose_name="是否管理员")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="api.strategyprofile",
                        verbose_name="策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户列表",
                "permissions": (
                    ("view_task", "Can see available tasks"),
                    ("change_task_status", "Can change the status of tasks"),
                    ("close_task", "Can remove a task by setting its status as closed"),
                ),
            },
            managers=[
                ("objects", api.models_user.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AddressBookProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.CharField(max_length=60, unique=True, verbose_name="地址簿GUID")),
                ("name", models.CharField(max_length=60, verbose_name="地址簿名称")),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("rule", models.IntegerField(default=1, verbose_name="共享权限")),
                ("info", models.JSONField(blank=True, default=dict, verbose_name="扩展信息")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_book_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "地址簿",
                "verbose_name_plural": "地址簿列表",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AddressBookRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("rule", models.IntegerField(default=1, verbose_name="共享权限")),
                ("is_everyone", models.BooleanField(default=False)),
                ("target_key", models.CharField(editable=False, max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_book_rules",
                        to="auth.group",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="api.addressbookprofile"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_book_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "地址簿规则",
                "verbose_name_plural": "地址簿规则列表",
            },
        ),
        migrations.CreateModel(
            name="AddressBookRuleAudit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=32)),
                ("target_type", models.CharField(max_length=16)),
                ("target_name", models.CharField(blank=True, default="", max_length=120)),
                ("rule", models.IntegerField(default=1, verbose_name="共享权限")),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_book_rule_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_audits",
                        to="api.addressbookprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "地址簿规则审计",
                "verbose_name_plural": "地址簿规则审计列表",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AddressBookShare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("rule", models.IntegerField(default=1, verbose_name="共享权限")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="api.addressbookprofile"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_book_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "地址簿共享",
                "verbose_name_plural": "地址簿共享列表",
            },
        ),
        migrations.CreateModel(
            name="AlarmLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("typ", models.IntegerField(default=0, verbose_name="Type")),
                ("info", models.JSONField(blank=True, default=dict, verbose_name="Info")),
                ("reporter_device_id", models.CharField(max_length=16, verbose_name="Reporter Device ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created At")),
                (
                    "reporter_device_uuid",
                    models.CharField(blank=True, default="", max_length=344, verbose_name="Reporter Device UUID"),
                ),
                ("conn_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="Connection ID")),
                ("audit_ref", models.CharField(blank=True, default="", max_length=256, verbose_name="Audit Reference")),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_alarm_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "告警日志",
                "verbose_name_plural": "告警日志列表",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ConnLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="GUID")),
                ("conn_id", models.PositiveIntegerField(verbose_name="Connection ID")),
                ("from_ip", models.GenericIPAddressField(verbose_name="From IP")),
                ("from_id", models.CharField(blank=True, default="", max_length=16, verbose_name="From ID")),
                ("rid", models.CharField(max_length=16, verbose_name="To ID")),
                ("conn_start", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Connected")),
                ("conn_end", models.DateTimeField(blank=True, null=True, verbose_name="Disconnected")),
                ("session_id", models.CharField(max_length=60, verbose_name="Session ID")),
                ("uuid", models.CharField(max_length=344, verbose_name="uuid")),
                ("conn_type", models.IntegerField(blank=True, null=True, verbose_name="Conn Type")),
                (
                    "primary_auth",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Primary Authentication"),
                ),
                ("two_factor", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Second Factor")),
                ("audit_ref", models.CharField(blank=True, default="", max_length=256, verbose_name="Audit Reference")),
                ("note", models.TextField(blank=True, default="", verbose_name="Note")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_connection_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_connection_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "连接日志",
                "verbose_name_plural": "连接日志列表",
                "ordering": ("-conn_start",),
            },
        ),
        migrations.CreateModel(
            name="FileLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.CharField(max_length=500, verbose_name="Path")),
                ("remote_id", models.CharField(default="0", max_length=16, verbose_name="Remote ID")),
                ("user_id", models.CharField(default="0", max_length=16, verbose_name="User ID")),
                ("user_ip", models.GenericIPAddressField(verbose_name="User IP")),
                ("filesize", models.PositiveBigIntegerField(default=0, verbose_name="Filesize")),
                ("direction", models.IntegerField(default=0, verbose_name="Direction")),
                (
                    "logged_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Logged At"),
                ),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Details")),
                (
                    "reporter_device_uuid",
                    models.CharField(blank=True, default="", max_length=344, verbose_name="Reporter Device UUID"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_file_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "文件传输日志",
                "verbose_name_plural": "文件传输日志列表",
                "ordering": ("-logged_at",),
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                ("username", models.CharField(blank=True, default="", max_length=150, verbose_name="用户名")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
            ],
            options={
                "verbose_name": "失败登录",
                "verbose_name_plural": "失败登录列表",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["ip", "username", "-created_at"], name="login_attempt_scope_lookup")],
            },
        ),
        migrations.CreateModel(
            name="OidcIdentity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issuer", models.URLField(max_length=512, verbose_name="Issuer")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("provider", models.CharField(max_length=64, verbose_name="Provider")),
                (
                    "last_username",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Last Username"),
                ),
                ("last_email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Last Email")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC身份",
                "verbose_name_plural": "OIDC身份列表",
                "ordering": ("issuer", "subject"),
            },
        ),
        migrations.CreateModel(
            name="OidcPendingAuth",
            fields=[
                ("state", models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="State")),
                (
                    "poll_code_hash",
                    models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Poll Code Hash"),
                ),
                ("provider", models.CharField(max_length=64, verbose_name="Provider")),
                (
                    "request_ip",
                    models.GenericIPAddressField(db_index=True, default="0.0.0.0", verbose_name="Request IP"),
                ),
                ("rid", models.CharField(blank=True, default="", max_length=16, verbose_name="Camellia ID")),
                ("device_uuid", models.CharField(blank=True, default="", max_length=344, verbose_name="Device UUID")),
                ("device_info", models.JSONField(blank=True, default=dict, verbose_name="Device Info")),
                ("nonce", models.CharField(max_length=64, verbose_name="OIDC Nonce")),
                ("code_verifier", models.CharField(max_length=128, verbose_name="PKCE Code Verifier")),
                ("status", models.CharField(db_index=True, default="pending", max_length=16, verbose_name="Status")),
                ("error_code", models.CharField(blank=True, default="", max_length=64, verbose_name="Error Code")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                (
                    "authenticated_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_oidc_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC待处理授权",
                "verbose_name_plural": "OIDC待处理授权列表",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RemoteDevice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rid", models.CharField(max_length=16, unique=True, verbose_name="客户端ID")),
                ("cpu", models.CharField(max_length=100, verbose_name="CPU")),
                ("hostname", models.CharField(max_length=100, verbose_name="主机名")),
                ("memory", models.CharField(max_length=100, verbose_name="内存")),
                ("os", models.CharField(max_length=100, verbose_name="操作系统")),
                ("uuid", models.CharField(max_length=344, unique=True, verbose_name="uuid")),
                (
                    "public_key_hash",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True, unique=True, verbose_name="设备公钥哈希"
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100, verbose_name="系统用户名")),
                ("version", models.CharField(max_length=100, verbose_name="客户端版本")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "address_book_name",
                    models.CharField(blank=True, default="", max_length=60, verbose_name="地址簿名称"),
                ),
                (
                    "address_book_tag",
                    models.CharField(blank=True, default="", max_length=60, verbose_name="地址簿标签"),
                ),
                (
                    "address_book_alias",
                    models.CharField(blank=True, default="", max_length=60, verbose_name="地址簿别名"),
                ),
                (
                    "address_book_password",
                    api.encrypted_fields.EncryptedTextField(
                        blank=True, default="", max_length=128, verbose_name="地址簿密码"
                    ),
                ),
                ("address_book_note", models.TextField(blank=True, default="", verbose_name="地址簿备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="设备注册时间")),
                ("update_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="设备更新时间")),
                (
                    "device_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="api.devicegroup",
                        verbose_name="设备组",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="api.strategyprofile",
                        verbose_name="直接分配策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备列表",
                "ordering": ("-rid",),
            },
        ),
        migrations.CreateModel(
            name="RemoteTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag_name", models.CharField(max_length=64, verbose_name="标签名称")),
                ("tag_color", models.CharField(blank=True, max_length=32, verbose_name="标签颜色")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="api.addressbookprofile",
                        verbose_name="地址簿",
                    ),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签列表",
                "ordering": ("profile_id", "tag_name"),
            },
        ),
        migrations.CreateModel(
            name="RemotePeer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rid", models.CharField(max_length=16, verbose_name="客户端ID")),
                ("username", models.CharField(blank=True, default="", max_length=100, verbose_name="系统用户名")),
                ("hostname", models.CharField(blank=True, default="", max_length=100, verbose_name="操作系统名")),
                ("alias", models.CharField(blank=True, default="", max_length=100, verbose_name="别名")),
                ("platform", models.CharField(blank=True, default="", max_length=100, verbose_name="平台")),
                (
                    "rhash",
                    api.encrypted_fields.EncryptedTextField(
                        blank=True, default="", max_length=256, verbose_name="设备链接密码"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "password",
                    api.encrypted_fields.EncryptedTextField(
                        blank=True, default="", max_length=60, verbose_name="共享密码"
                    ),
                ),
                ("device_group_name", models.CharField(blank=True, default="", max_length=60, verbose_name="设备组")),
                ("login_name", models.CharField(blank=True, default="", max_length=60, verbose_name="登录账号")),
                ("same_server", models.BooleanField(default=False, verbose_name="同服务器")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peers",
                        to="api.addressbookprofile",
                        verbose_name="地址簿",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="peers", to="api.remotetag", verbose_name="标签"),
                ),
            ],
            options={
                "verbose_name": "客户端",
                "verbose_name_plural": "客户端列表",
                "ordering": ("profile_id", "rid"),
            },
        ),
        migrations.CreateModel(
            name="RemoteToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_token",
                    models.CharField(editable=False, max_length=64, unique=True, verbose_name="access_token"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="登录时间")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_token",
                        to="api.remotedevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "令牌",
                "verbose_name_plural": "令牌列表",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("shash", models.CharField(max_length=64, unique=True, verbose_name="链接Key哈希")),
                ("token_prefix", models.CharField(max_length=12, verbose_name="链接前缀")),
                ("is_used", models.BooleanField(default=False, verbose_name="是否使用")),
                ("is_expired", models.BooleanField(default=False, verbose_name="是否过期")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="生成时间")),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, default=api.models_work.share_link_expiry, verbose_name="过期时间"
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="使用时间")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "peers",
                    models.ManyToManyField(related_name="share_links", to="api.remotepeer", verbose_name="机器列表"),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "分享链接",
                "verbose_name_plural": "链接列表",
                "ordering": ("-create_time",),
            },
        ),
        migrations.AddField(
            model_name="devicegroup",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="device_groups",
                to="api.strategyprofile",
                verbose_name="策略",
            ),
        ),
        migrations.AddConstraint(
            model_name="addressbookprofile",
            constraint=models.UniqueConstraint(fields=("owner", "name"), name="unique_address_book_name_per_owner"),
        ),
        migrations.AddConstraint(
            model_name="addressbookprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("rule__gte", 1), ("rule__lte", 3)), name="valid_address_book_profile_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="addressbookrule",
            constraint=models.UniqueConstraint(
                fields=("profile", "target_key"), name="unique_address_book_rule_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="addressbookrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("rule__gte", 1), ("rule__lte", 3)), name="valid_address_book_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="addressbookrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", True), ("is_everyone", True), ("user__isnull", True)),
                    models.Q(("group__isnull", True), ("is_everyone", False), ("user__isnull", False)),
                    models.Q(("group__isnull", False), ("is_everyone", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="one_address_book_rule_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="addressbookruleaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(("rule__gte", 1), ("rule__lte", 3)), name="valid_address_book_audit_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="addressbookruleaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_type__in", ("user", "group", "everyone"))),
                name="valid_address_book_audit_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="addressbookshare",
            constraint=models.UniqueConstraint(fields=("profile", "user"), name="unique_address_book_share_user"),
        ),
        migrations.AddConstraint(
            model_name="addressbookshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("rule__gte", 1), ("rule__lte", 3)), name="valid_address_book_share_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="alarmlog",
            constraint=models.CheckConstraint(
                condition=models.Q(("typ__in", (0, 1, 2, 6, 7, 8, 9))), name="valid_alarm_type"
            ),
        ),
        migrations.AddIndex(
            model_name="connlog",
            index=models.Index(fields=["rid", "session_id", "from_id"], name="connection_participant_lookup"),
        ),
        migrations.AddIndex(
            model_name="connlog",
            index=models.Index(fields=["-conn_start"], name="connection_started_lookup"),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.UniqueConstraint(fields=("rid", "uuid", "session_id"), name="unique_connection_session"),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conn_end__isnull", True), ("conn_end__gte", models.F("conn_start")), _connector="OR"
                ),
                name="connection_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.CheckConstraint(condition=models.Q(("conn_id__gte", 1)), name="positive_connection_id"),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("primary_auth__isnull", True),
                    models.Q(("primary_auth__gte", 1), ("primary_auth__lte", 4)),
                    _connector="OR",
                ),
                name="valid_primary_auth_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("two_factor__isnull", True),
                    models.Q(("two_factor__gte", 1), ("two_factor__lte", 2)),
                    _connector="OR",
                ),
                name="valid_second_factor_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conn_type__isnull", True), models.Q(("conn_type__gte", 0), ("conn_type__lte", 4)), _connector="OR"
                ),
                name="valid_connection_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="filelog",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", (0, 1))), name="valid_file_transfer_direction"
            ),
        ),
        migrations.AddConstraint(
            model_name="oidcidentity",
            constraint=models.UniqueConstraint(fields=("issuer", "subject"), name="unique_oidc_issuer_subject"),
        ),
        migrations.AddConstraint(
            model_name="oidcpendingauth",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("pending", "done", "error"))), name="valid_oidc_pending_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="remotetag",
            constraint=models.UniqueConstraint(fields=("profile", "tag_name"), name="unique_tag_per_address_book"),
        ),
        migrations.AddConstraint(
            model_name="remotepeer",
            constraint=models.UniqueConstraint(fields=("profile", "rid"), name="unique_peer_per_address_book"),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["creator", "is_used", "is_expired", "expires_at"], name="share_link_active_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_used", True), ("used_at__isnull", False), ("used_by__isnull", False)),
                    models.Q(("is_used", False), ("used_at__isnull", True), ("used_by__isnull", True)),
                    _connector="OR",
                ),
                name="consistent_share_link_consumption",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"), name="unique_username_case_insensitive"
            ),
        ),
    ]
