# Generated by Django 6.0.7 on 2026-08-04 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remotetoken_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcpendingauth',
            name='device_proof',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='remotedevice',
            name='deployment_generation',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='DeviceProofChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('login', 'Password login'), ('oidc', 'OIDC login'), ('deploy', 'Deployment')], max_length=16)),
                ('rid', models.CharField(max_length=16)),
                ('device_uuid', models.CharField(max_length=344)),
                ('public_key_hash', models.CharField(max_length=64)),
                ('deployment_generation', models.PositiveBigIntegerField(default=0)),
                ('request_ip', models.GenericIPAddressField(db_index=True, default='0.0.0.0')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proof_challenges', to='api.remotedevice')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_proof_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['request_ip', 'expires_at'], name='device_proof_ip_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceRecoveryApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_device_recoveries', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_approvals', to='api.remotedevice')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['device', 'public_key_hash', 'expires_at'], name='device_recovery_lookup_idx')],
            },
        ),
    ]
