# Generated by Django 6.0.7 on 2026-08-05 13:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_profile_snapshots(apps, schema_editor):
    audit_model = apps.get_model("api", "AddressBookRuleAudit")
    database = schema_editor.connection.alias
    for audit in audit_model.objects.using(database).select_related("profile", "profile__owner").iterator():
        profile = audit.profile
        if profile is None:
            continue
        audit.profile_guid = str(profile.guid or "")
        audit.profile_name = str(profile.name or "")
        audit.profile_owner_name = getattr(profile.owner, "username", "") or ""
        audit.save(
            using=database,
            update_fields=("profile_guid", "profile_name", "profile_owner_name"),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_addressbookprofile_default_password"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="addressbookruleaudit",
            name="valid_address_book_audit_target",
        ),
        migrations.AddField(
            model_name="addressbookruleaudit",
            name="profile_guid",
            field=models.CharField(db_index=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="addressbookruleaudit",
            name="profile_name",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="addressbookruleaudit",
            name="profile_owner_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.RunPython(backfill_profile_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="addressbookruleaudit",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rule_audits",
                to="api.addressbookprofile",
            ),
        ),
        migrations.AlterField(
            model_name="addressbookruleaudit",
            name="target_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddConstraint(
            model_name="addressbookruleaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_type__in", ("user", "group", "everyone", "profile"))),
                name="valid_address_book_audit_target",
            ),
        ),
    ]
