# Generated by Django 6.0.7 on 2026-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_remove_addressbookruleaudit_valid_address_book_audit_target_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestRateBucket",
            fields=[
                (
                    "key_hash",
                    models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
                ),
                ("scope", models.CharField(editable=False, max_length=24)),
                ("group", models.CharField(editable=False, max_length=32)),
                ("window_seconds", models.PositiveSmallIntegerField(editable=False)),
                ("used", models.PositiveBigIntegerField(default=0, editable=False)),
                ("expires_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("expires_at", "key_hash"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("window_seconds__gte", 1), ("window_seconds__lte", 3600)),
                        name="valid_rate_bucket_window",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestRateLease",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("request_id", models.CharField(editable=False, max_length=32)),
                ("key_hash", models.CharField(editable=False, max_length=64)),
                ("scope", models.CharField(editable=False, max_length=24)),
                ("group", models.CharField(editable=False, max_length=32)),
                ("expires_at", models.DateTimeField(db_index=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("expires_at", "pk"),
                "indexes": [
                    models.Index(fields=["key_hash", "expires_at"], name="rate_lease_key_exp_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request_id", "key_hash"),
                        name="unique_rate_lease_request_key",
                    )
                ],
            },
        ),
    ]
