# Generated by Django 6.0.7 on 2026-08-05 16:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_requestratebucket_requestratelease"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingUpload",
            fields=[
                ("upload_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("create_id", models.UUIDField(editable=False)),
                ("owner_id_at_create", models.PositiveBigIntegerField(editable=False)),
                ("deployment_generation", models.PositiveBigIntegerField(editable=False)),
                ("filename", models.CharField(editable=False, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("finalized", "Finalized"), ("aborted", "Aborted")],
                        default="active",
                        editable=False,
                        max_length=12,
                    ),
                ),
                ("committed_offset", models.PositiveBigIntegerField(default=0, editable=False)),
                ("revision", models.PositiveBigIntegerField(default=0, editable=False)),
                ("expected_size", models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ("expected_digest", models.CharField(blank=True, default="", editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "heartbeat_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finalized_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("aborted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording_uploads",
                        to="api.remotedevice",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "upload_id"),
            },
        ),
        migrations.CreateModel(
            name="RecordingUploadChunk",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_id", models.UUIDField(editable=False)),
                ("offset", models.PositiveBigIntegerField(editable=False)),
                ("length", models.PositiveIntegerField(editable=False)),
                ("digest", models.CharField(editable=False, max_length=64)),
                ("revision", models.PositiveBigIntegerField(editable=False)),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="api.recordingupload",
                    ),
                ),
            ],
            options={
                "ordering": ("upload_id", "revision"),
            },
        ),
        migrations.AddConstraint(
            model_name="recordingupload",
            constraint=models.UniqueConstraint(fields=("device", "create_id"), name="unique_recording_create_id"),
        ),
        migrations.AddConstraint(
            model_name="recordingupload",
            constraint=models.UniqueConstraint(fields=("device", "filename"), name="unique_recording_filename"),
        ),
        migrations.AddConstraint(
            model_name="recordingupload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("aborted_at__isnull", True),
                        ("expected_digest", ""),
                        ("expected_size__isnull", True),
                        ("finalized_at__isnull", True),
                        ("state", "active"),
                    ),
                    models.Q(
                        ("aborted_at__isnull", True),
                        ("expected_size__isnull", False),
                        ("finalized_at__isnull", False),
                        ("state", "finalized"),
                    )
                    & ~models.Q(("expected_digest", "")),
                    models.Q(
                        ("aborted_at__isnull", False),
                        ("expected_digest", ""),
                        ("expected_size__isnull", True),
                        ("finalized_at__isnull", True),
                        ("state", "aborted"),
                    ),
                    _connector="OR",
                ),
                name="valid_recording_upload_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingupload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_size__isnull", True), ("committed_offset", models.F("expected_size")), _connector="OR"
                ),
                name="recording_final_size_committed",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingupload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("committed_offset", 0), ("revision", 0)),
                    models.Q(("committed_offset__gte", 1), ("revision__gte", 1)),
                    _connector="OR",
                ),
                name="valid_recording_upload_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordinguploadchunk",
            constraint=models.UniqueConstraint(fields=("upload", "chunk_id"), name="unique_recording_chunk_id"),
        ),
        migrations.AddConstraint(
            model_name="recordinguploadchunk",
            constraint=models.UniqueConstraint(fields=("upload", "revision"), name="unique_recording_chunk_revision"),
        ),
        migrations.AddConstraint(
            model_name="recordinguploadchunk",
            constraint=models.UniqueConstraint(fields=("upload", "offset"), name="unique_recording_chunk_offset"),
        ),
        migrations.AddConstraint(
            model_name="recordinguploadchunk",
            constraint=models.CheckConstraint(
                condition=models.Q(("length__gte", 1)), name="positive_recording_chunk_length"
            ),
        ),
        migrations.AddConstraint(
            model_name="recordinguploadchunk",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="positive_recording_chunk_revision"
            ),
        ),
    ]
