# Generated by Django 6.0.7 on 2026-08-05 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_recording_upload_state_machine"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionAuditEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(editable=False, unique=True)),
                ("sequence", models.PositiveBigIntegerField(editable=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("authorized", "Authorized"),
                            ("controller_bound", "Controller bound"),
                            ("note", "Note"),
                            ("file", "File"),
                            ("alarm", "Alarm"),
                            ("closed", "Closed"),
                        ],
                        editable=False,
                        max_length=24,
                    ),
                ),
                ("actor_id_at_event", models.PositiveBigIntegerField(editable=False)),
                ("reporter_device_uuid", models.CharField(blank=True, default="", editable=False, max_length=344)),
                ("details", models.JSONField(blank=True, default=dict, editable=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                "ordering": ("connection_id", "sequence"),
            },
        ),
        migrations.AddField(
            model_name="alarmlog",
            name="audit_version",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="alarmlog",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarm_logs",
                to="api.connlog",
            ),
        ),
        migrations.AddField(
            model_name="connlog",
            name="audit_version",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="connlog",
            name="controller_device",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controlled_connection_audits",
                to="api.remotedevice",
            ),
        ),
        migrations.AddField(
            model_name="connlog",
            name="controller_device_generation",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="connlog",
            name="controller_device_id_at_bind",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="connlog",
            name="controller_owner_id_at_bind",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="connlog",
            name="create_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="connlog",
            name="event_revision",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="connlog",
            name="host_device",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connection_audits",
                to="api.remotedevice",
            ),
        ),
        migrations.AddField(
            model_name="connlog",
            name="host_device_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="connlog",
            name="host_device_id_at_create",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="connlog",
            name="owner_id_at_create",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="filelog",
            name="audit_version",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="filelog",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_logs",
                to="api.connlog",
            ),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("audit_version", 2)),
                fields=("host_device", "create_id"),
                name="unique_connection_audit_create",
            ),
        ),
        migrations.AddConstraint(
            model_name="connlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("audit_version", 1),
                    models.Q(
                        ("audit_version", 2),
                        ("create_id__isnull", False),
                        ("event_revision__gte", 1),
                        ("host_device_id_at_create__isnull", False),
                        ("owner_id_at_create__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="valid_connection_audit_authority",
            ),
        ),
        migrations.AddField(
            model_name="connectionauditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connection_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="connectionauditevent",
            name="connection",
            field=models.ForeignKey(
                editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="events", to="api.connlog"
            ),
        ),
        migrations.AddField(
            model_name="alarmlog",
            name="event",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarm_log",
                to="api.connectionauditevent",
            ),
        ),
        migrations.AddField(
            model_name="filelog",
            name="event",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_log",
                to="api.connectionauditevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarmlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("audit_version", 1),
                    models.Q(("audit_version", 2), ("connection__isnull", False), ("event__isnull", False)),
                    _connector="OR",
                ),
                name="valid_alarm_audit_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="filelog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("audit_version", 1),
                    models.Q(("audit_version", 2), ("connection__isnull", False), ("event__isnull", False)),
                    _connector="OR",
                ),
                name="valid_file_audit_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectionauditevent",
            constraint=models.UniqueConstraint(
                fields=("connection", "sequence"), name="unique_connection_audit_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="connectionauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)), name="positive_connection_audit_sequence"
            ),
        ),
    ]
