# Generated by Django 6.0.7 on 2026-08-06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("api", "0018_connection_audit_lease")]

    operations = [
        migrations.CreateModel(
            name="FileTransferAuditEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("revision", models.PositiveBigIntegerField(editable=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("progress", "Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("unknown", "Unknown"),
                        ],
                        editable=False,
                        max_length=12,
                    ),
                ),
                ("transferred_bytes", models.PositiveBigIntegerField(default=0, editable=False)),
                (
                    "terminal_reason",
                    models.CharField(blank=True, default="", editable=False, max_length=256),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("file_transfer", "File transfer"),
                            ("clipboard", "Clipboard"),
                            ("printer", "Printer"),
                        ],
                        default="file_transfer",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={"ordering": ("transfer_id", "revision")},
        ),
        migrations.RemoveConstraint(
            model_name="filelog",
            name="valid_file_audit_binding",
        ),
        migrations.AddField(
            model_name="filelog",
            name="is_file",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="filelog",
            name="planned_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="filelog",
            name="planned_file_count",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="filelog",
            name="sample_files",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="filelog",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("file_transfer", "File transfer"),
                    ("clipboard", "Clipboard"),
                    ("printer", "Printer"),
                ],
                default="file_transfer",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="filelog",
            name="started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="filelog",
            name="state",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("progress", "Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="filelog",
            name="terminal_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="filelog",
            name="terminal_reason",
            field=models.CharField(blank=True, default="", editable=False, max_length=256),
        ),
        migrations.AddField(
            model_name="filelog",
            name="transfer_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="filelog",
            name="transfer_revision",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="filelog",
            name="transferred_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="filelog",
            index=models.Index(fields=["connection", "state"], name="file_transfer_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="filelog",
            constraint=models.CheckConstraint(
                condition=models.Q(audit_version=1)
                | models.Q(audit_version__in=(2, 3), connection__isnull=False, event__isnull=False)
                | models.Q(
                    audit_version=4,
                    connection__isnull=False,
                    event__isnull=False,
                    started_at__isnull=False,
                    transfer_id__isnull=False,
                    transfer_revision__gte=1,
                    transferred_bytes__lte=models.F("planned_bytes"),
                ),
                name="valid_file_audit_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="filelog",
            constraint=models.CheckConstraint(
                condition=~models.Q(audit_version=4)
                | models.Q(
                    state__in=("started", "progress"),
                    terminal_at__isnull=True,
                    terminal_reason="",
                )
                | models.Q(
                    state="completed",
                    terminal_at__isnull=False,
                    terminal_reason="",
                )
                | models.Q(
                    state__in=("failed", "cancelled", "unknown"),
                    terminal_at__isnull=False,
                    terminal_reason__gt="",
                ),
                name="valid_file_transfer_lifecycle",
            ),
        ),
        migrations.AddField(
            model_name="filetransferauditevent",
            name="connection_event",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_transfer_events",
                to="api.connectionauditevent",
            ),
        ),
        migrations.AddField(
            model_name="filetransferauditevent",
            name="transfer",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_events",
                to="api.filelog",
            ),
        ),
        migrations.AddConstraint(
            model_name="filetransferauditevent",
            constraint=models.UniqueConstraint(
                fields=("transfer", "revision"),
                name="unique_file_transfer_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="filetransferauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(revision__gte=1),
                name="positive_file_transfer_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="filetransferauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    state__in=("started", "progress", "completed"),
                    terminal_reason="",
                )
                | models.Q(
                    state__in=("failed", "cancelled", "unknown"),
                    terminal_reason__gt="",
                ),
                name="valid_file_transfer_event_state",
            ),
        ),
    ]
