# Generated by Django 6.0.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("api", "0019_file_audit_lifecycle")]

    operations = [
        migrations.AddField(
            model_name="connlog",
            name="controller_device_name_at_bind",
            field=models.CharField(blank=True, default="", editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="connlog",
            name="host_device_name_at_create",
            field=models.CharField(blank=True, default="", editable=False, max_length=100),
        ),
    ]
