# Generated by Django 6.0.7 on 2026-08-07

import api.audit_expressions
import django.contrib.postgres.indexes
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


POSTGRES_INDEXES = (
    (
        "user_name_search_trgm_idx",
        'CREATE INDEX CONCURRENTLY "user_name_search_trgm_idx" '
        'ON "api_userprofile" USING GIN ((UPPER(("username")::text)) gin_trgm_ops)',
    ),
    (
        "ab_audit_created_pk_idx",
        'CREATE INDEX CONCURRENTLY "ab_audit_created_pk_idx" '
        'ON "api_addressbookruleaudit" ("created_at" DESC, "id" DESC)',
    ),
    (
        "ab_audit_search_trgm_idx",
        'CREATE INDEX CONCURRENTLY "ab_audit_search_trgm_idx" '
        'ON "api_addressbookruleaudit" USING GIN '
        "((UPPER((COALESCE((\"profile_name\")::text, '') || ' ' || "
        "COALESCE((\"profile_guid\")::text, '') || ' ' || "
        "COALESCE((\"profile_owner_name\")::text, '') || ' ' || "
        "COALESCE((\"target_name\")::text, '') || ' ' || "
        "COALESCE((\"action\")::text, ''))::text)) gin_trgm_ops)",
    ),
    (
        "alarm_created_pk_idx",
        'CREATE INDEX CONCURRENTLY "alarm_created_pk_idx" ON "api_alarmlog" ("created_at" DESC, "id" DESC)',
    ),
    (
        "alarm_type_created_pk_idx",
        'CREATE INDEX CONCURRENTLY "alarm_type_created_pk_idx" ON "api_alarmlog" ("typ", "created_at" DESC, "id" DESC)',
    ),
    (
        "alarm_search_trgm_idx",
        'CREATE INDEX CONCURRENTLY "alarm_search_trgm_idx" '
        'ON "api_alarmlog" USING GIN '
        "((UPPER((COALESCE((\"reporter_device_id\")::text, '') || ' ' || "
        "COALESCE((\"reporter_device_uuid\")::text, '') || ' ' || "
        "COALESCE((\"audit_ref\")::text, ''))::text)) gin_trgm_ops)",
    ),
)

SQLITE_INDEXES = (
    (
        "ab_audit_created_pk_idx",
        'CREATE INDEX "ab_audit_created_pk_idx" ON "api_addressbookruleaudit" ("created_at" DESC, "id" DESC)',
    ),
    (
        "alarm_created_pk_idx",
        'CREATE INDEX "alarm_created_pk_idx" ON "api_alarmlog" ("created_at" DESC, "id" DESC)',
    ),
    (
        "alarm_type_created_pk_idx",
        'CREATE INDEX "alarm_type_created_pk_idx" ON "api_alarmlog" ("typ", "created_at" DESC, "id" DESC)',
    ),
)


def create_audit_indexes(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public")
        for name, statement in POSTGRES_INDEXES:
            # A failed concurrent build leaves an invalid index behind. Removing
            # the exact unpublished migration-owned name makes retries converge.
            schema_editor.execute(f'DROP INDEX CONCURRENTLY IF EXISTS "{name}"')
            schema_editor.execute(statement)
        return
    if vendor == "sqlite":
        for name, statement in SQLITE_INDEXES:
            schema_editor.execute(f'DROP INDEX IF EXISTS "{name}"')
            schema_editor.execute(statement)
        return
    raise RuntimeError(f"Unsupported database vendor for audit indexes: {vendor}")


def drop_audit_indexes(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        for name, _statement in reversed(POSTGRES_INDEXES):
            schema_editor.execute(f'DROP INDEX CONCURRENTLY IF EXISTS "{name}"')
        return
    if vendor == "sqlite":
        for name, _statement in reversed(SQLITE_INDEXES):
            schema_editor.execute(f'DROP INDEX IF EXISTS "{name}"')
        return
    raise RuntimeError(f"Unsupported database vendor for audit indexes: {vendor}")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("api", "0020_connection_device_name_snapshots")]

    operations = [
        migrations.AlterModelOptions(
            name="addressbookruleaudit",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "地址簿规则审计",
                "verbose_name_plural": "地址簿规则审计列表",
            },
        ),
        migrations.AlterModelOptions(
            name="alarmlog",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "告警日志",
                "verbose_name_plural": "告警日志列表",
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_audit_indexes, drop_audit_indexes)],
            state_operations=[
                migrations.AddIndex(
                    model_name="userprofile",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper(
                                django.db.models.functions.comparison.Cast("username", models.TextField())
                            ),
                            name="gin_trgm_ops",
                        ),
                        name="user_name_search_trgm_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="addressbookruleaudit",
                    index=models.Index(
                        fields=["-created_at", "-id"],
                        name="ab_audit_created_pk_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="addressbookruleaudit",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper(
                                django.db.models.functions.comparison.Cast(
                                    api.audit_expressions.AuditSearchDocument(
                                        "profile_name",
                                        "profile_guid",
                                        "profile_owner_name",
                                        "target_name",
                                        "action",
                                    ),
                                    models.TextField(),
                                )
                            ),
                            name="gin_trgm_ops",
                        ),
                        name="ab_audit_search_trgm_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="alarmlog",
                    index=models.Index(
                        fields=["-created_at", "-id"],
                        name="alarm_created_pk_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="alarmlog",
                    index=models.Index(
                        fields=["typ", "-created_at", "-id"],
                        name="alarm_type_created_pk_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="alarmlog",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper(
                                django.db.models.functions.comparison.Cast(
                                    api.audit_expressions.AuditSearchDocument(
                                        "reporter_device_id",
                                        "reporter_device_uuid",
                                        "audit_ref",
                                    ),
                                    models.TextField(),
                                )
                            ),
                            name="gin_trgm_ops",
                        ),
                        name="alarm_search_trgm_idx",
                    ),
                ),
            ],
        ),
    ]
