# Generated by Django 6.0.7 on 2026-08-08

from django.db import migrations, models


INDEXES = (
    (
        "device_owner_rid_idx",
        'ON "api_remotedevice" ("owner_id", "rid")',
    ),
    (
        "device_owner_active_rid_idx",
        'ON "api_remotedevice" ("owner_id", "is_active", "rid")',
    ),
    (
        "device_active_rid_idx",
        'ON "api_remotedevice" ("is_active", "rid")',
    ),
    (
        "device_owner_updated_rid_idx",
        'ON "api_remotedevice" ("owner_id", "update_time" DESC, "rid")',
    ),
)


def create_device_inventory_indexes(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor not in ("postgresql", "sqlite"):
        raise RuntimeError(f"Unsupported database vendor for device inventory indexes: {vendor}")
    concurrently = " CONCURRENTLY" if vendor == "postgresql" else ""
    for name, definition in INDEXES:
        schema_editor.execute(f'DROP INDEX{concurrently} IF EXISTS "{name}"')
        schema_editor.execute(f'CREATE INDEX{concurrently} "{name}" {definition}')


def drop_device_inventory_indexes(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor not in ("postgresql", "sqlite"):
        raise RuntimeError(f"Unsupported database vendor for device inventory indexes: {vendor}")
    concurrently = " CONCURRENTLY" if vendor == "postgresql" else ""
    for name, _definition in reversed(INDEXES):
        schema_editor.execute(f'DROP INDEX{concurrently} IF EXISTS "{name}"')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("api", "0021_audit_ordering_indexes")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_device_inventory_indexes,
                    drop_device_inventory_indexes,
                )
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="remotedevice",
                    index=models.Index(
                        fields=["owner", "rid"],
                        name="device_owner_rid_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="remotedevice",
                    index=models.Index(
                        fields=["owner", "is_active", "rid"],
                        name="device_owner_active_rid_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="remotedevice",
                    index=models.Index(
                        fields=["is_active", "rid"],
                        name="device_active_rid_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="remotedevice",
                    index=models.Index(
                        fields=["owner", "-update_time", "rid"],
                        name="device_owner_updated_rid_idx",
                    ),
                ),
            ],
        )
    ]
