# Generated by Django 6.0.7 on 2026-08-08

from django.db import migrations, models


CHECK_CONSTRAINT = models.CheckConstraint(
    condition=models.Q(reporter_sequence__isnull=True) | models.Q(reporter_sequence__gte=1),
    name="positive_audit_reporter_sequence",
)
UNIQUE_CONSTRAINT = models.UniqueConstraint(
    condition=models.Q(reporter_sequence__isnull=False),
    fields=("connection", "reporter_sequence"),
    name="unique_audit_reporter_sequence",
)


def create_audit_evidence_constraints(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            'ALTER TABLE "api_connectionauditevent" DROP CONSTRAINT IF EXISTS "positive_audit_reporter_sequence"'
        )
        schema_editor.execute(
            'ALTER TABLE "api_connectionauditevent" '
            'ADD CONSTRAINT "positive_audit_reporter_sequence" '
            'CHECK ("reporter_sequence" IS NULL OR "reporter_sequence" >= 1) NOT VALID'
        )
        schema_editor.execute(
            'ALTER TABLE "api_connectionauditevent" VALIDATE CONSTRAINT "positive_audit_reporter_sequence"'
        )
        schema_editor.execute('DROP INDEX CONCURRENTLY IF EXISTS "unique_audit_reporter_sequence"')
        schema_editor.execute(
            'CREATE UNIQUE INDEX CONCURRENTLY "unique_audit_reporter_sequence" '
            'ON "api_connectionauditevent" ("connection_id", "reporter_sequence") '
            'WHERE "reporter_sequence" IS NOT NULL'
        )
        return
    if vendor == "sqlite":
        model = apps.get_model("api", "ConnectionAuditEvent")
        original_constraints = model._meta.constraints
        model._meta.constraints = [*original_constraints, CHECK_CONSTRAINT]
        try:
            schema_editor.add_constraint(model, CHECK_CONSTRAINT)
        finally:
            model._meta.constraints = original_constraints
        schema_editor.add_constraint(model, UNIQUE_CONSTRAINT)
        return
    raise RuntimeError(f"Unsupported database vendor for audit evidence constraints: {vendor}")


def drop_audit_evidence_constraints(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute('DROP INDEX CONCURRENTLY IF EXISTS "unique_audit_reporter_sequence"')
        schema_editor.execute(
            'ALTER TABLE "api_connectionauditevent" DROP CONSTRAINT IF EXISTS "positive_audit_reporter_sequence"'
        )
        return
    if vendor == "sqlite":
        model = apps.get_model("api", "ConnectionAuditEvent")
        schema_editor.remove_constraint(model, UNIQUE_CONSTRAINT)
        schema_editor.remove_constraint(model, CHECK_CONSTRAINT)
        return
    raise RuntimeError(f"Unsupported database vendor for audit evidence constraints: {vendor}")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("api", "0022_device_inventory_indexes")]

    operations = [
        migrations.AddField(
            model_name="connectionauditevent",
            name="acknowledgement",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="connectionauditevent",
            name="payload_digest",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="connectionauditevent",
            name="reporter_device_generation",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="connectionauditevent",
            name="reporter_device_id_at_event",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="connectionauditevent",
            name="reporter_sequence",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_audit_evidence_constraints,
                    drop_audit_evidence_constraints,
                )
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="connectionauditevent",
                    constraint=CHECK_CONSTRAINT,
                ),
                migrations.AddConstraint(
                    model_name="connectionauditevent",
                    constraint=UNIQUE_CONSTRAINT,
                ),
            ],
        ),
    ]
